# Generated by Django 6.0.2 on 2026-02-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/'),
        ),
    ]
